### ISSUE TITLE
double precision 2D camera support

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#34] opened 2019-01-18 01:20 UTC
can't have `varying double` in GLSL afaik, so it would have to use single precision `vec2` for pixel grid (centered on `0` to avoid precision loss) then convert and offset in the fragment portion.

doing something like this manually in my frags, but have to keep `Center` on 0 otherwise it breaks.

**Comment by 3Dickulus** [comment] 2019-01-18 05:10
GL version clash between varying and double? will in/out work? or is  there restriction on passing double between vertex and fragment parts?
 I opted for QVector suite over Syntopia's original vector 2D/3D/4D classes because of the handy builtin functions and because, at the time, double types weren't even on the radar. The camera object(s) use the FloatWidget classes so they should handle double types, there are 3 places I think will be causing the problem, Camera2D::transform, Camera2D::mouseDown and Camera2D::centerDown are using QVector types ( screenTo3D in Camera2D class is a dummy ) Down means "captured when mouse button clicked" so these values are only being captured as float types?

**Comment by claudeha** [comment] 2019-01-18 05:37
there is restriction on passing `smooth` interpolated `double` between vertex and fragment parts (`flat` works, but that is useless for our purposes)

**Comment by claudeha** [comment] 2019-01-18 05:37
Does the `glm` header-only C++ GLSL-alike maths library support `double`?

**Comment by claudeha** [comment] 2019-01-18 11:50
> Does the `glm` header-only C++ GLSL-alike maths library support `double`?

yes it does. https://glm.g-truc.net/0.9.9/api/a00699.html

**Comment by 3Dickulus** [comment] 2019-01-19 01:42
might be good to move to glm, will have to let this idea percolate for a while, I think that getting around something that is a built in restiction in GLSL should be left to the fragment code but I am open to ideas

**Comment by claudeha** [comment] 2019-01-23 00:51
> should be left to the fragment code

but dragging and zooming in the view with the mouse is nice to have, and is currently broken with the fragment code workarounds I've tried.

**Comment by 3Dickulus** [comment] 2019-01-24 00:58
yeah, I noticed that and fixed it, dragging and zooming in the view with the mouse works fine with both double test frags (looking at it now both your mandel and my burningship) it was late and I can't remember exactly what fixed it, looking at the diff I only see changes to do with log slider tests ???

**Comment by claudeha** [comment] 2019-01-29 02:22
in my tests, it "worked" only up to a certain depth - going deep enough and the translation was quantized.  but I can't test until I get a replacement mobo...

**Comment by claudeha** [comment] 2019-08-06 23:46
Mouse wheel zoom and drag is broken (quantized) at deep zooms due to `QVector3D` storing `float` internally (precision loss in `Center`)

The current `log_Zoom` thing isn't really logarithmic, can't do the full range to 1e16 (when neighbouring pixels merge) without breaking the slider (uninteractable), maybe it should just be `slider[-16,0,16]` and let the .frag do `float Zoom = pow(10.0, log_Zoom)` itself?  the `Camera2D` code would need some changes for zoom unpacking/repacking (exp10/log10). Don't need full `double` precision for `Zoom` anyway afaict, just `Center`.

**Comment by 3Dickulus** [comment] 2019-08-07 01:14
if this is entirely due to QVector3D@float prec then a number of things should be solved by moving to GLM. I like Qt classes for all of the built in stuff but I'm sure GLM has equivalents.

I note that in qvector3d.h Qt only uses qreal(double) in one function...
```
Q_DECL_CONSTEXPR inline QPointF QVector3D::toPointF() const
{
    return QPointF(qreal(xp), qreal(yp));
}
```
...the rest are all explicitly float, they need to Template it or use qreal everywhere and I can't fix that unless I convert ALL qvector headers and code to qreal and recompile Qt :( not wanting to distribute a heavily modified version of Qt just to make FragM work with doubles. Moving to GLM sounds much more appealing.

**Comment by claudeha** [comment] 2019-08-07 13:07
As well as the pull request to use glm instead of QVectorND, to fix the quantization I did this (because smooth varyings are only single precision)

    --- old/Fragmentarium-Source/Examples/Include/Progressive2D-4.frag	2019-03-21 20:21:59.550027973 +0000
    +++ new/Fragmentarium-Source/Examples/Include/Progressive2D-4.frag	2019-08-06 23:49:39.653902183 +0100
    @@ -25,8 +25,8 @@
      double ar = pixelSize.y/pixelSize.x;
      gl_Position =  gl_Vertex;
      viewCoord = gl_Vertex.xy;
    -	coord = vec2(((gl_ProjectionMatrix*gl_Vertex).xy*vec2(ar,1.0))/float(Zoom)+  vec2(Center));
    +	coord = vec2(((gl_ProjectionMatrix*gl_Vertex).xy*vec2(ar,1.0))/float(Zoom));
     }
     
     #endvertex
    @@ -63,12 +63,13 @@
     #endif
     
     uniform int subframe;
    +uniform dvec2 Center;
     
     dvec2 rand(dvec2 co){
      // implementation found at: lumina.sourceforge.net/Tutorials/Noise.html
    @@ -107,7 +108,7 @@
      } // else {  w =pow( 1.0-length(r),1.0);};
     
      r*=AARange;
    -	dvec2 c = coord.xy+aaScale*r;
    +	dvec2 c = coord.xy+aaScale*r + Center;
     #ifdef linearGamma
      dvec3 color =  color(c);
     #else

**Comment by 3Dickulus** [comment] 2019-08-07 23:11
Thank you claudeha! I was looking forward to hacking at this but you seem to have it handled, I will test a few things but in general if you replaced all occurrences of QVectorND and anything related to them with GLM equivalents (double) it should be good to go...

shortly before your recent pull requests I hacked together a "jump to error line" patch that works nicely so no more guessing or comparing preprocessed script to figure out what the cause was, it can be adjusted from preferences to jump to line on error or warn or both or none, it only jumps to the first one but it does make debugging a lot easier. I will push this (j2e) patch after some testing with your most recent contributions.

todo: add GLM and OpenEXR repositories to FragM repo ;)

**Comment by claudeha** [comment] 2019-08-08 10:13
On 2019-08-08 00:11, 3Dickulus wrote:
> Thank you claudeha! I was looking forward to hacking at this but you
> seem to have it handled, I will test a few things but in general if
> you replaced all occurrences of QVectorND and anything related to them
> with GLM equivalents (double) it should be good to go...

:)

> shortly before your recent pull requests I hacked together a "jump to
> error line" patch that works nicely so no more guessing or comparing
> preprocessed script to figure out what the cause was, it can be
> adjusted from preferences to jump to line on error or warn or both or
> none, it only jumps to the first one but it does make debugging a lot
> easier. I will push this (j2e) patch after some testing with your most
> recent contributions.

Great!

Click on message in log to jump to error would be awesome, especially if 
it worked with included frags.

> todo: add GLM and OpenEXR repositories to FragM repo ;)

as git submodule rather than direct files, I hope. Would prefer to use 
distro libs so I hope that will still be possible.

**Comment by 3Dickulus** [comment] 2019-08-09 00:59
As sub modules. Yes distro libs are best that's why I haven't done that yet.
OpenEXR has some interesting features re:versions
https://github.com/mitsuba-renderer/openexr/blob/master/IlmBase/README.namespacing

The log is not treated as separate lines, the entire log is inserted into one line widget, a little parsing could break it up and make it possible to select each one.

**Comment by 3Dickulus** [comment] 2019-08-09 02:55
>   As well as the pull request to use glm instead of QVectorND, to fix the quantization I did this (because smooth varyings are only single precision)
line 91 needs to be 	`dvec4 new = color(coord.xy + Center);` as well.

ok I'm sold on GLM will merge #47 a little more discussion required for GL versioning though...

**Closed** 2019-08-09 03:04 UTC
Labels: enhancement, help wanted
