### ISSUE TITLE
no image feedback in big-tile animation rendering

### ISSUE THREAD

**Issue by claudeha** [3Dickulus/FragM#114] opened 2020-01-29 03:28 UTC
**Describe the bug**
When rendering an animation to disk and the image size is the same size as the display window, the image is displayed (which is nice to check that all is going ok).  When the animation tile size is larger than the window size (I think, not sure of exact cause), the window doesn't update and it's necessary to check the image files on disk to see if all is going ok.

**To Reproduce**
1. Load a cheap-to-render frag
2. Drag widgets to make display window 960x540 pixels
3. Render animation with 1 tile at 1920x1080, 1 subframe
4. See error: window is not updated during rendering
5. Render animation with 1 tile at 960x540 pixels, 1 subframe
6. See okness: window is updated

**Expected behavior**
Window updates with the image of the current frame.

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Gfx card AMD RX 580

**Comment by 3Dickulus** [comment] 2020-01-29 05:02
if tile size is larger than window render area it does not update the screen, scaling issues or something, don't recall exactly but it is not a bug, it is intended behaviour but can be changed

also, updates after tile is rendered and if there is only one tile you might not see the update before rendering the next frame starts

**Comment by 3Dickulus** [comment] 2020-02-06 00:36
gl4dev branch doesn't update at all... yet.

**Comment by 3Dickulus** [comment] 2020-02-17 08:06
fixed in gl4dev branch in commit 0f852d4

tile size independent, look at MainWindow::renderTiled() for cheap/dirty (really simple) way to render image tiles over GL area ;) had to cheat a bit but it's simple and nets the same effect so gl4dev now updates as tiles are rendered.

**Comment by 3Dickulus** [comment] 2020-03-04 03:38
oops, updates on first anim frame but not after that, fixed the first bit but neglected to test further...

so on the todo list.

**Comment by 3Dickulus** [comment] 2020-03-04 04:59
ok fixed in v2.5 rev 2

**Closed by 3Dickulus** 2020-03-04 04:59 UTC
